// <auto-generated />
namespace LoteAutos2017.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADDTABLAS_USUARIO_PERMISOS_ROLES_PERMISOSNEGADOS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDTABLAS_USUARIO_PERMISOS_ROLES_PERMISOSNEGADOS));
        
        string IMigrationMetadata.Id
        {
            get { return "201703081819332_ADD-TABLAS_USUARIO_PERMISOS_ROLES_PERMISOSNEGADOS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
